name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]

# Environment variables
env:
  app_location: "/hello-world"
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
